### ISSUE TITLE
Cal scraper updated on main project - need to advance this too

### ISSUE THREAD

**Issue by sohodf** [daniel-hauser/moneyman#127]
Hi Daniel, and thank you for this project.
I'm using your docker to easily export my transactions for json.
a few weeks ago it stopped working for Cal due to their site updating.
I've opened an [issue ](https://github.com/eshaham/israeli-bank-scrapers/issues/763) on the [main project](https://github.com/baruchiro/israeli-bank-scrapers), and they fixed it.
Can you advance your project to use that project's latest.

**Comment by daniel-hauser** [comment]
Although https://github.com/eshaham/israeli-bank-scrapers/issues/763 was merged, the fix is not yet published.

The release pipeline is blocked on https://github.com/eshaham/israeli-bank-scrapers/pull/771, once my PR merges and the new version is published to npm - moneyman will be updated to use it.

**Comment by sohodf** [comment]
Amazing. Thank you :)

**Comment by sohodf** [comment]
@daniel-hauser - are we sure that everything is updated? i've pruned, re-pull and rebuilt the docker image, and still getting a timeout on the Cal scraper.
