### ISSUE TITLE
Hash transaction undefined

### ISSUE THREAD

**Issue by roisec** [daniel-hauser/moneyman#132]
Hi,
I am getting a lot of multiple visacal transactions because the hash function contains issue with undefined object - 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/68992144/233498256-35bf7339-7d00-49e8-b08b-f6b9b1f8bd04.png">

**Comment by daniel-hauser** [comment]
Thanks for reporting.

After investigating, the new cal scraper added in https://github.com/eshaham/israeli-bank-scrapers/pull/767 has no `memo` field.
Since this field is part of the hash - the value is undefined and makes it into the hash string.
https://github.com/daniel-hauser/moneyman/blob/b41963e7dbc04bd25b3aa280f6622fb0c0fffd52/src/storage/index.ts#L50

I can add an empty string when undefined, but the meaning is that all users will get duplications for transactions that already scraped with undefined so I prefer not to.

**Comment by roisec** [comment]
Hi Daniel @daniel-hauser 
I think it's cause the opossite,
Because currently I have transaction without undefined , and when I am run the latest version the he added all the transactions with duplicate. 
Is it  correct?

**Comment by roisec** [comment]
@daniel-hauser WDYT?

**Comment by daniel-hauser** [comment]
After checking my transaction I understood that we indeed need a fix here - opened #134
