### ISSUE TITLE
Disable HIDDEN_DEPRECATIONS

### ISSUE THREAD

**Issue by roisec** [daniel-hauser/moneyman#345]
Hi 
I am trying to disable the deprecated messages.
Which value should I set on HIDDEN_DEPRECATIONS?

**Comment by daniel-hauser** [comment]
Currently the only deprecation message is for the hash change.  to disable it add `HIDDEN_DEPRECATIONS=hashFiledChange`.
As a side note, I'm planning to make the new hash as the default so i suggest moving to it if possible.

**Comment by roisec** [comment]
Hi @daniel-hauser thanks, 
If I moving to the new hash value , it will not apply for older transactions? It will update seamlessly without any duplication or issues?

**Comment by daniel-hauser** [comment]
https://github.com/daniel-hauser/moneyman/blob/b433fd006deac0f8d16b320fe74ed68ad276fd4a/src/storage/sheets.ts#L108:L120

> Hi @daniel-hauser thanks, If I moving to the new hash value , it will not influence for older transactions? Correct? It will update seamlessly for newer transactions without any duplication or issues?

This depends on what storage you are using.
In the sheets storage, since all hashes are fetched - i do check both the old and new hash.
For other storages you will need to manually dedupe the overlapping suggestions (by default 10 days of overlap)
